### ISSUE TITLE
Nog steeds veel errors

### ISSUE THREAD

**Issue by Theo-denBlanken** [29269/FRO#2]
is er wel een update geweest? Online en hier opGitHub??

**Comment by Duneyasaleh** [comment]
Omg ik moest nog de goede link nog sturen sorry meneer

Deze werkt wel en op GitHub ook
http://29269.hosts2.ma-cloud.nl/bewijzenmap/periode1.1/opdracht7/http://29269.hosts2.ma-cloud.nl/bewijzenmap/periode1.1/opdracht7/<http://29269.hosts2.ma-cloud.nl/bewijzenmap/periode1.1/opdracht7/http:/29269.hosts2.ma-cloud.nl/bewijzenmap/periode1.1/opdracht7/>

GitHub:

https://github.com/29269/FRO/tree/master/opdracht7

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

Van: Theo den Blanken<mailto:notifications@github.com>
Verzonden: woensdag 27 november 2019 22:19
Aan: 29269/FRO<mailto:FRO@noreply.github.com>
CC: Subscribed<mailto:subscribed@noreply.github.com>
Onderwerp: [29269/FRO] Nog steeds veel errors (#2)


is er wel een update geweest? Online en hier opGitHub??

**Comment by Duneyasaleh** [comment]
nieuw url
