### ISSUE TITLE
nog 1 error

### ISSUE THREAD

**Issue by Theo-denBlanken** [29269/FRO#4]
`legend` kan alleen een child zijn van `fieldset`. Vele divs heb je om een mooi randje gemaakt. Dat kan dus beter met fieldset

**Comment by Duneyasaleh** [comment]
geen error meer

**Comment by Theo-denBlanken** [comment]
Dag Dunya,

Nieuwe versie nog online plaatsen

met vriendelijke groeten,
-


[ma-logo]
Theo den Blanken
        [Theo] <http://blanken5.home.xs4all.nl/>
docent
Mediadeveloper
Mediacollege Amsterdam  [Twitter] <https://twitter.com/theodenblanken/>  [WordPress] <http://bla.hosts.ma-cloud.nl/>




Op 5 dec. 2019, om 10:00 heeft Duneya <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Closed #4<https://github.com/29269/FRO/issues/4>.
